title: <p> Saravanan Thiyagarajan </p>
logo: /assets/img/Saravanan.JPG

description: 
  <p> 
  <a href="https://www.linkedin.com/in/saravanan-t-66607537">LinkedIn</a> |
  <a href="https://github.com/sarthiya">GitHub</a>
  </p>


theme: jekyll-theme-minimal
