title: <p align="center"> Saravanan Thiyagarajan </p>
logo: /assets/img/Saravanan.JPG
description: 
  <a style="text-align:center" href="https://in.linkedin.com/in/saravanan-thiyagarajan-66607537">LinkedIn</a> |
  <a style="text-align:center" href="https://github.com/sarthiya">GitHub</a>


theme: jekyll-theme-minimal
