title: <p align="center"> Saravanan Thiyagarajan </p>
logo: <p align="center"> /assets/img/Saravanan.JPG </p>
description: 
  <p align="center"> 
  <a href="https://in.linkedin.com/in/saravanan-thiyagarajan-66607537">LinkedIn</a> |
  <a href="https://github.com/sarthiya">GitHub</a>
  </p>


theme: jekyll-theme-minimal
