title: <p align="center"> Saravanan Thiyagarajan </p>
logo: /assets/img/Saravanan.JPG
description: 
  <p align="center">
  <br>   
  I am very excited about learning Data Science since 2021. Working as a Software Engineering Manager, specialized in delivering web applications using Agile methodologies in last 5 years. Also, I've worked extensively developing Video Control plane and Consumer electronics applications for 11+ years before starting to manage projects.
  <br>
  </p>

theme: jekyll-theme-minimal
